//
//  Ratings.swift
//  MySampleApp
//
//
// Copyright 2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.21
//

import Foundation
import UIKit
import AWSDynamoDB

class Rating: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _id: String?
    var _isLender: String?
    var _raterId: String?
    var _subjectId: String?
    var _value: NSNumber?
    
    class func dynamoDBTableName() -> String {
 
        return "stylerentbackend-mobilehub-1070684980-Ratings"
    }
    
    class func hashKeyAttribute() -> String {

        return "_id"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_id" : "id",
               "_isLender" : "isLender",
               "_raterId" : "rater_id",
               "_subjectId" : "subject_id",
               "_value" : "value",
        ]
    }
}
