//
//  Conversations.swift
//  MySampleApp
//
//
// Copyright 2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.21
//

import Foundation
import UIKit
import AWSDynamoDB

@objcMembers
class Conversation: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _channelUrl: String?
    var _listingId: String?
    var _purchaserId: String?
    var _sellerId: String?
    
    class func dynamoDBTableName() -> String {

        return "stylerentbackend-mobilehub-1070684980-Conversations"
    }
    
    class func hashKeyAttribute() -> String {

        return "_channelUrl"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_channelUrl" : "channelUrl",
               "_listingId" : "listingId",
               "_purchaserId" : "purchaserId",
               "_sellerId" : "sellerId",
        ]
    }
}
