//
//  Rentals.swift
//  MySampleApp
//
//
// Copyright 2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.21
//

import Foundation
import UIKit
import AWSDynamoDB

@objcMembers
class Rental: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _id: String?
    var _borrowerId: String?
    var _isActive: NSNumber?
    var _lenderId: String?
    var _listingId: String?
    var _returnDate: String?
    var _startDate: String?
    
    class func dynamoDBTableName() -> String {

        return "stylerentbackend-mobilehub-1070684980-Rentals"
    }
    
    class func hashKeyAttribute() -> String {

        return "_id"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_id" : "id",
               "_borrowerId" : "borrowerId",
               "_isActive" : "isActive",
               "_lenderId" : "lenderId",
               "_listingId" : "listingId",
               "_returnDate" : "returnDate",
               "_startDate" : "startDate",
        ]
    }
}
