//
//  Users.swift
//  MySampleApp
//
//
// Copyright 2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.21
//

import Foundation
import UIKit
import AWSDynamoDB

@objcMembers
class User: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _id: String?
    var _name: String?
	var _authType: String?
	var _password: String?
	var _stripeId: String?
	var _pushEndpoint: String?
	var _balance : NSNumber?
    
    class func dynamoDBTableName() -> String {

        return "stylerentbackend-mobilehub-1070684980-Users"
    }
    
    class func hashKeyAttribute() -> String {

        return "_id"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_id" : "id",
               "_name" : "name",
			   "_authType" : "authType",
			   "_password" : "password",
			   "_stripeId" : "stripeId",
			   "_pushEndpoint" : "pushEndpoint",
			   "_balance" : "balance"
        ]
    }
}
